spring:
  application:
    name: cart-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cart-service
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 60000

cart:
  client:
    platzi: https://api.escuelajs.co/api/v1